# Check out https://pre-commit.com/ for documentation
# and https://pre-commit.com/hooks.html for more hooks
minimum_pre_commit_version: 2.15.0
# Don't set language_version -- it's only useful if we have multiple
# python versions or our build uses a different env than runtime
repos:
  # --- Meta hooks ---
  #- hooks:
  # This one is useful, but it will fail if, e.g., you don't have a single yaml file
  #  - id: check-hooks-apply
  # This one will fail, e.g., if you don't have a recipes/ file, which is excluded here
  #   - id: check-useless-excludes
  #  repo: meta

  # --- Built-in hooks --
-   hooks:
    -   id: check-symlinks
    -   id: check-case-conflict
    -   id: fix-byte-order-marker
    -   id: end-of-file-fixer
        exclude: ^tests/resources/
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-json
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-docstring-first
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: check-yaml
        exclude: ^recipes/.*
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0

  # --- Commit msg checks ---
-   hooks:
    -   id: commitizen
        stages: [commit-msg]
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.35.0

  # --- Strip output from .ipynb files ---
  # - hooks:
  #     - id: nbstripout
  #       files: ".ipynb"
  #   repo: https://github.com/kynan/nbstripout
  #   rev: 0.5.0

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
  # Formatters
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: pretty-format-yaml
        args: [--autofix, --indent, '4']
-   repo: https://github.com/BlankSpruce/gersemi #cmake formatter
    rev: 0.8.2
    hooks:
    -   id: gersemi
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.0.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/psf/black # python formatter
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs

  # --- Linters ---
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
    -   id: mypy
        additional_dependencies: [pandas-stubs, numpy, types-requests]
        args: [--ignore-missing-imports, --config-file=pyproject.toml]
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-bugbear == 20.11.1
        language_version: python3.8
        args: [--config=tox.ini]

-   repo: https://github.com/cmake-lint/cmake-lint
    rev: 1.4.2
    hooks:
    -   id: cmakelint
        args: [--linelength=120]
-   repo: https://github.com/cpplint/cpplint
    rev: 1.6.1
    hooks:
    -   id: cpplint
        args: [--linelength=120, '--filter=-legal/copyright,-whitespace/braces,-whitespace/newline,-build/namespaces,-build/header_guard,-build/include_order,-build/include_subdir, -whitespace/parens,-readability/casting,-runtime/threadsafe_fn,-runtime/int,-runtime/printf,-whitespace/operators,-readability/braces,-whitespace/comma,-whitespace/tab,-readability/fn_size']
