[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "numpy>=1.21",
  "scikit-build",
  "cmake>=3.22",
  "ninja; platform_system!='Windows'"
]
build-backend = "setuptools.build_meta"


[tool.mypy]
plugins = ["numpy.typing.mypy_plugin"]
